[project]
name = "pymol-mcp"
version = "0.1.0"
description = "Control PyMOL from Claude via the Model Context Protocol (MCP)"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Vishnu Rajan Tejus" },
    { name = "Jonathan Ward" },
]
keywords = ["mcp", "pymol", "structural-biology", "molecular-visualization"]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "mcp[cli]>=1.0.0",
    "uvicorn>=0.32.1",
    "httpx>=0.28.1",
]

[tool.pyright]
include = ["pymol_mcp_server.py", "models.py"]
venvPath = "."
venv = ".venv"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.uv]
dev-dependencies = ["pyright>=1.1.379", "pytest>=8.3.3", "ruff>=0.6.9"]
